info:
  app:
    name: "Submissões de Artigos"
    description: "Projeto para submissões de artigos científicos em eventos"
    version: "0.0.1.SNAPSHOT"

spring:
  jpa:
    hibernate:
        ddl-auto: none
    show-sql: true
    properties:
        hibernate.hbm2ddl.auto: validate
#    properties:
#        hibernate:
#            hbm2ddl:
#                ddl-auto: create-drop
#                auto: validate
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    url: "jdbc:h2:file:~/db/submissoes"
    username: "sa"
    password:
    driver-class-name: org.h2.Driver

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "health, env, metrics, sessions, mappings, info, liquibase"
